name: onethreethreeseven
author: KHM9
main: onethreethreeseven\Main
version: "1.0.1"
description: onethreethreeseven is very useless
api:
- 3.0.0

main: onethreethreeseven
commands: []
permissions: []
